language: android
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - android-21
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-license-.+
    - .+
jdk: oraclejdk8

before_install:
  - cd outlay
  
script: ./gradlew clean assembleDebug


notifications:
  email:
    recipients:
    - laszlo.tamas94@gmail.com
    on_failure: always
    on_success: always